mainApp/urls.py
from django.urls import path, include, re_path
from mainApp.views import (CategoryListView, CategoryDetailView, 
							PostListView, PostDetailView, 
							CreateCommentView, LikeDislikeView,
							RegistrationView, ContactsView,
							LoginView, UserAccountView,
							AddArticleToFavorites)
from django.contrib.auth import logout
from django.contrib.auth.views import LogoutView
from django.urls import reverse_lazy


urlpatterns = [
	path('contacts/', ContactsView.as_view(), name = 'contacts'),
	path('add_comment/', CreateCommentView.as_view(), name = 'add_comment'),
	path('like_dislike/', LikeDislikeView.as_view(), name = 'like_dislike'),
	path('registration/', RegistrationView.as_view(), name = 'registration'),
	path('login/', LoginView.as_view(), name = 'login_page'),
	path('u/<user>/', UserAccountView.as_view(), name = 'user_detail'),
	path('logout/', LogoutView.as_view(next_page = reverse_lazy('wrapper')), name = 'logout_action'),
	path('add_to_favorites/', AddArticleToFavorites.as_view(), name = 'add_to_favorites'),
	path('posts/', PostListView.as_view(), name = 'posts'),
	path('', CategoryListView.as_view(), name = 'wrapper'),

	path('<slug>/', CategoryDetailView.as_view(), name = 'category_detail'),
	path('<category>/<slug>/', PostDetailView.as_view(), name = 'post_detail'),

	
]

myblog/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('mainApp.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

mainApp/models.py
from django.db import models
from django.contrib.auth.models import User
from django.urls import reverse
from django.contrib.contenttypes.models import ContentType
from django.contrib.contenttypes.fields import GenericForeignKey, GenericRelation

# Create your models here.

class Category(models.Model):
	
	name = models.CharField(max_length = 20, unique = True)
	slug = models.SlugField()

	def __str__(self):
		return self.name

	def get_absolute_url(self):
		return reverse('category_detail', kwargs = {'slug' :self.slug})


def generate_filename(instance, filename):
	filename = instance.slug + '.jpg'
	return f"{instance}/{filename}"

class Post(models.Model):
	
	title = models.CharField(max_length = 100)
	date_published = models.DateTimeField(auto_now_add = True)
	slug = models.SlugField()
	text = models.TextField()
	image = models.ImageField(upload_to = generate_filename)
	likes = models.PositiveIntegerField(default = 0)
	dislikes = models.PositiveIntegerField(default = 0)
	user = models.ForeignKey('auth.User', on_delete = models.CASCADE)
	category = models.ForeignKey('Category', on_delete = models.CASCADE)
	comments = GenericRelation('comments')
	reaction = models.ManyToManyField('auth.User', blank = True, related_name = 'user_reaction_for_post')

	class Meta:
		ordering = ["-date_published"]

	def __str__(self):
		return self.title

	def text_preview(self):
		return self.text[:300] + '...'

	def get_absolute_url(self):
		return reverse('post_detail', kwargs = {'slug':self.slug, 'category':self.category.slug})

	#def __eq__(self, other):
	#	return self.title == other.title and self.text == other.text

class Comments(models.Model):
	
	author = models.ForeignKey('auth.User', on_delete = models.CASCADE)
	comment = models.CharField(max_length = 140)
	timestamp = models.DateTimeField(auto_now_add = True, auto_now = False)

	object_id = models.PositiveIntegerField()
	content_type = models.ForeignKey(ContentType, on_delete = models.CASCADE)
	content_object = GenericForeignKey('content_type', 'object_id')

class UserAccount(models.Model):

	nick = models.OneToOneField('auth.User', on_delete = models.CASCADE)
	first_name = models.CharField(max_length = 20)
	last_name = models.CharField(max_length = 30)
	email = models.EmailField()
	favorite_posts = models.ManyToManyField(Post)

	def __str__(self):
		return self.nick.username

	def full_name(self):
		return f"{self.first_name} {self.last_name}"

	def get_absolute_url(self): #for difficult url
		return reverse('user_detail', kwargs = {'user':self.nick.username})

mainApp/forms.py
from django import forms
from django.contrib.auth import get_user_model

User = get_user_model() 

class CommentForm(forms.Form):
	
	comment = forms.CharField(widget = forms.Textarea)

class LoginForm(forms.Form):

	username = forms.CharField()
	password = forms.CharField(widget = forms.PasswordInput)

	def clean(self):
		username = self.cleaned_data['username']
		password = self.cleaned_data['password']

		if not User.objects.filter(username = username).exists():
			raise forms.ValidationError('User with that username doesnt exist')

		user = User.objects.get(username = username)
		
		if not user.check_password(password):
			raise forms.ValidationError('Password is not right')

		

class RegisrationForm(forms.ModelForm): 

	password = forms.CharField(widget = forms.PasswordInput)
	password_check = forms.CharField(widget = forms.PasswordInput)

	class Meta:

		model = User
		fields = ['username', 'password', 'password_check', 'first_name', 'last_name', 'email']

	
	def __init__(self, *args, **kwargs):
		super(RegisrationForm, self).__init__(*args, **kwargs)
		#self.fields['username'].label = 'пользовательский ник' #Overloaded and make labels with another language
		self.fields['username'].help_text = 'Required. 30 characters or fewer. Letters, digits and @/./+/-/_ only.'

	def clean(self):
		username = self.cleaned_data['username']
		password = self.cleaned_data['password']
		password_check = self.cleaned_data['password_check']

		if User.objects.filter(username = username).exists():
			raise forms.ValidationError('User with that username already exists')

		if password != password_check:
			raise forms.ValidationError('Passwords dont equal')

	

mainApp/views.py
from django.shortcuts import render
from django.views.generic.list import ListView
from django.views.generic.detail import DetailView
from mainApp.models import Category, Post, UserAccount
from mainApp.forms import CommentForm, RegisrationForm, LoginForm
from django.views.generic.base import View
from django.http import JsonResponse, HttpResponseRedirect
from django.contrib.auth import get_user_model, authenticate, login, logout
from mainApp.mixins import CategoryListMixin
from django.core.paginator import EmptyPage, PageNotAnInteger, Paginator

# Create your views here.

User = get_user_model()

class CategoryListView(ListView):
		
	model = Category
	template_name = 'mainApp/wrapper.html'

	def get_context_data(self, *args, **kwargs):
		context = super(CategoryListView, self).get_context_data(*args, **kwargs)
		context['categories'] = self.model.objects.all()
		return context

class CategoryDetailView(DetailView, CategoryListMixin):
	model = Category
	template_name = 'mainApp/category_detail.html' # url((

	def get_context_data(self, *args, **kwargs):
		context = super(CategoryDetailView, self).get_context_data(*args, **kwargs)
		context['category'] = self.get_object()
		context['posts'] = Post.objects.filter(category = self.get_object()).all()
		return context

class PostListView(ListView, CategoryListMixin):
	model = Post
	template_name = 'mainApp/posts.html'

	def get_context_data(self, *args, **kwargs):
		context = super(PostListView, self).get_context_data(*args, **kwargs)
		#context['posts'] = self.model.objects.all()
		post_list = self.model.objects.all()
		paginator = Paginator(post_list, 3)
		page = self.request.GET.get('page')
		posts = paginator.get_page(page)
		context['posts'] = posts
		return context

class PostDetailView(DetailView):
	model = Post
	template_name = 'mainApp/post_detail.html'
	context_object_name = 'post_detail'

	def get_context_data(self, *args, **kwargs):
		context = super(PostDetailView, self).get_context_data(*args, **kwargs)
		context['post'] = self.get_object()
		context['post_comments'] = self.get_object().comments.all()
		context['form'] = CommentForm()
		
		if not self.request.user.is_anonymous:
			context['current_user'] = UserAccount.objects.get(nick = self.request.user)

		return context

class CreateCommentView(View):

	template_name = 'mainApp/post_detail.html'

	def post(self, request, *args, **kwargs): #posting comment; if i wanna get it than get *GET*
		post_detail_id = self.request.POST.get('post_detail_id')
		comment = self.request.POST.get('comment')
		post = Post.objects.get(id = post_detail_id)
		new_comment = post.comments.create(author = request.user, comment = comment)
		comment = [{'author':new_comment.author.username, 
					'comment': new_comment.comment, 
					'timestamp':new_comment.timestamp}]

		return JsonResponse(comment, safe = False)

class LikeDislikeView(View):

	template_name = 'mainApp/post_detail.html'

	def get(self, request, *args, **kwargs):
		post_detail_id = self.request.GET.get('post_detail_id')
		post = Post.objects.get(id = post_detail_id)
		like = self.request.GET.get('like')
		dislike = self.request.GET.get('dislike')
		
		if like and (request.user not in post.reaction.all()):
			post.likes += 1 
			post.reaction.add(request.user)
			post.save()
		
		if dislike and (request.user not in post.reaction.all()):
			post.dislikes += 1 
			post.reaction.add(request.user)
			post.save()
		
		data = {
			'like':post.likes,
			'dislike':post.dislikes 
		}

		return JsonResponse(data)
		
class RegistrationView(View):

	template_name = 'mainApp/registration.html'

	def get(self, request, *args, **kwargs):
		form = RegisrationForm(request.POST or None)
		context = {'form':form}
		return render(self.request, self.template_name, context)

	def post(self, request, *args, **kwargs):
		form = RegisrationForm(request.POST or None)
		
		if form.is_valid():
			new_user = form.save(commit = False)
			username = form.cleaned_data['username']
			password = form.cleaned_data['password']
			password_check = form.cleaned_data['password_check']
			new_user.set_password(password)
			first_name = form.cleaned_data['first_name']
			last_name = form.cleaned_data['last_name']
			email = form.cleaned_data['email']
			new_user.save()
			UserAccount.objects.create(nick = User.objects.get(username = new_user.username),
										first_name = new_user.first_name,
										last_name = new_user.last_name,
										email = new_user.email)
		
			return HttpResponseRedirect('/')

		context = {'form':form}
		return render(self.request, self.template_name, context)

class LoginView(View):

	template_name = 'mainApp/login.html'

	def get(self, request, *args, **kwargs):
		form = LoginForm()
		context = {'form':form}
		return render(self.request, self.template_name, context)

	def post(self, request, *args, **kwargs):
		form = LoginForm(request.POST or None)
		
		if form.is_valid():
			username = form.cleaned_data['username']
			password = form.cleaned_data['password']
			user = authenticate(username = username, password = password)

			if user:
				login(self.request, user) 
				return HttpResponseRedirect('/')

		context = {'form':form}
		return render(self.request, self.template_name, context)


class UserAccountView(View):

	template_name = 'mainApp/user_detail.html'

	def get(self, request, *args, **kwargs):
		user = self.kwargs.get('user')
		current_user = UserAccount.objects.get(nick = User.objects.get(username = user))
		context = {'current_user':current_user}
		return render(self.request, self.template_name, context)

class AddArticleToFavorites(View):

	template_name = 'mainApp/post_detail.html'

	def get(self, request, *args, **kwargs):
		post_detail_slug = self.request.GET.get('post_detail_slug')
		post = Post.objects.get(slug = post_detail_slug)
		current_user = UserAccount.objects.get(nick = self.request.user)
		current_user.favorite_posts.add(post)
		current_user.save()
		return JsonResponse({'ok':'ok'})


class ContactsView(View):

	template_name = "mainApp/contacts.html"

	def get(self, request, *args, **kwargs):
		context = {
			'name':'Harry Potter',
			'address':'Hogwarts Castle',
			'email':'harrypotter@ukr.net'
		}
		return render(self.request, self.template_name, context)
																

mainApp/templates/mainApp/category_detail.html
{% extends "mainApp/wrapper.html" %}

{% block content %}
	<div class="container">
		{% if posts %}
			<h3>Posts by category {{ category.name }}:</h3>
			<ul>
				{%  for post in posts %}
					<li>
						<a href="{% url 'post_detail' post.category.slug post.slug %}">{{ post.title }}</a>
					</li>
				{%  endfor %}	
			</ul>
		{% else %}
				<h4>Category doesn't have posts...</h4>
		{%  endif %}
	</div>
{% endblock %}

mainApp/templates/mainApp/contacts.html
{% extends "mainApp/wrapper.html" %}

{% block content %}
	<h4>Contact name: {{ name }}</h4>
	<h4>Addres: {{ address }}</h4>
	<h4>Email: {{ email }}</h4>
{% endblock %}

mainApp/templates/mainApp/login.html
{% extends "mainApp/wrapper.html" %}

{%  load crispy_forms_tags %}

{%  block content %}
	<div class="container">
		<h4>Log In</h4>
		<div class="row">
			<div class="col-sm-6 col-sm-offset-2">
				<form action="" method="POST">
					{{  form.error }}
					{% csrf_token %}
					{{  form|crispy }}
					<input type="submit" value="Log In">
				</form>
			</div>
		</div>
	</div>
{% endblock %}

mainApp/templates/mainApp/post_detail.html
{% extends "mainApp/wrapper.html" %}

{%  load crispy_forms_tags %} <!--for better forms-->

{% block content %}
	<style type="text/css">
		.head {margin-bottom: 10px;}
		.user{margin-right: 10px;}
		hr {border-top: 1px solid #000 !important;}
	</style>
	<!--Post detail-->
	<div id="img_class" style="height:200px; width:300px;">
		<img src="/media/{{ post_detail.image }}" style="margin:0px auto;
															display:block;
															max-width:100%; 
  															max-height:100%;" >
  	</div>
  	<br><br>
	<h4 align="center">{{ post_detail.title }}</h4><br>
	<p>{{ post_detail.text }}</p><br>
	
	<!--Likes and dislikes for post-->
	<a href="#" id="like">
		<span class="glyphicon glyphicon-thumbs-up" style="color: green;"></span>
	</a>
	<span id="liked">{{ post_detail.likes }}</span>
	<a href="#" id="dislike" style="padding-left: 25px;">
		<span class="glyphicon glyphicon-thumbs-down" style="color: red"></span>
	</a>
	<span id="disliked">{{ post_detail.dislikes }}</span>
	<br><br>

	<!--Add to favorites button-->
	<p class="add_to_favorites-{{ post_detail.slug }}">
		{% if not request.user.is_anonymous %}
			{%  if post_detail in current_user.favorite_posts.all %}
				<button class="btn btn-disabled">Added to favorites</button>
			{% else %}
				<a href="#" class="post_detail" data-slug="{{ post_detail.slug }}">
					<button class="btn btn-danger">Add in favorites</button>
				</a>
			{% endif %}
		{% endif %}
	</p>
	<p class="post_added-{{ post_detail.slug }}"></p>

	<h4>Comments:</h4>
	<hr>

	<div class="container new_comment">	
	</div>

	{%  for com in post_comments%}
		<div class="container">
			<div class="row comment">
			    <div class="head">
			        <small>
			        	<strong class="user">{{ com.author.username }}</strong>
			        	{{ com.timestamp }}
			        </small>
			        <br>
			    </div>    
			    <p>{{ com.comment|safe }}</p>
			</div>
		</div>
	{%  endfor %}

	{% if not request.user.is_anonymous %}
	<div class="col-sm-7 col-sm-offset-2">
		<form action="" method="POST">
			<input type="hidden" id="post" data-id="{{ post_detail.id }}">
			{% csrf_token %}
			{{ form|crispy }}
			<input type="submit" value="Add comment" id="add_comment" data-toggle="modal" data-target="#myModal">
		</form>
	</div>
	{% endif %}
	<!--Doesn't work 'cause server gives error 500-->
	<div class="modal fade" id="myModal" role="dialog">
	    <div class="modal-dialog">
	    
	      <!-- Modal content-->
	      <div class="modal-content">
	        <div class="modal-header">
	          <button type="button" class="close" data-dismiss="modal">&times;</button>
	          <h4 class="modal-title">Header</h4>
	        </div>
	        <div class="modal-body">
	          <p>Comment was added</p>
	        </div>
	        <div class="modal-footer">
	          <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
	        </div>
	      </div>
	      
	    </div>
  	</div>

  	<!--Add comments-->
	<script type="text/javascript">
		$(document).ready(function() {
			function getCookie(name) {   //for generating csrf token
    			var cookieValue = null;
    			if (document.cookie && document.cookie !== '') {
        			var cookies = document.cookie.split(';');
        			for (var i = 0; i < cookies.length; i++) {
            			var cookie = jQuery.trim(cookies[i]);
            			// Does this cookie string begin with the name we want?
            			if (cookie.substring(0, name.length + 1) === (name + '=')) {
                			cookieValue = decodeURIComponent(cookie.substring(name.length + 1));
                			break;
            			}
        			}
    			}
    			return cookieValue;
			}
			var csrftoken = getCookie('csrftoken');
			$('#add_comment').on('click', function(e){
				e.preventDefault()
				var post_detail_id = $('#post').attr('data-id')
				var comment = $('#id_comment').val()
				
				data = {
					post_detail_id: post_detail_id,
					comment: comment,
					csrfmiddlewaretoken:csrftoken
				}

				$.ajax({
					type:"POST",
					url:"{% url 'add_comment' %}",
					dataType:"json",
					data:data,
					success: function(data){
						$.each(data, function(field) {
							$('.new_comment').prepend('<div class="row comment"><div class="head"><small><strongclass="user">' + data[field]['author'] + '</strong>'+ data[field]['timestamp'] + 
								'</small><br></div><p>' + data[field]['comment'] + 
								'</p></div></div>')
								$('#id_comment').val('') 
						})
					}
				})
			})
		})
	</script>
	<!--Work with likes/dislikes-->
	<script type="text/javascript">
		$(document).ready(function(){
			$('#like').on('click', function(e){
				e.preventDefault()
				var like = 'like'
				var post_detail_id = $('#post').attr('data-id')

				data = {
					post_detail_id:post_detail_id,
					like:like
				}

				$.ajax({
					type:"GET",
					url:"{% url 'like_dislike' %}",
					dataType:"json",
					data:data,
					success: function(data){
						$('#liked').html(data.like)
						$('#disliked').html(data.dislike)
					}
				})
			})
		})

		$(document).ready(function(){
			$('#dislike').on('click', function(e){
				e.preventDefault()
				var dislike = 'dislike'
				var post_detail_id = $('#post').attr('data-id')

				data = {
					post_detail_id:post_detail_id,
					dislike:dislike
				}

				$.ajax({
					type:"GET",
					url:"{% url 'like_dislike' %}",
					dataType:"json",
					data:data,
					success: function(data){
						$('#liked').html(data.like)
						$('#disliked').html(data.dislike)
					}
				})
			})
		})
	</script>
	<!--Add to favorites script-->
	<script type="text/javascript">
		$(document).ready(function(){
			$('.post_detail').on('click', function(e){
				e.preventDefault()
				var post_detail_slug = $(this).attr('data-slug')

				data = {
					post_detail_slug:post_detail_slug
				}

				$.ajax({
					type:"GET",
					url:"{% url 'add_to_favorites' %}",
					dataType:"json",
					data:data,
					success:function(data){
						$('.add_to_favorites-'+ post_detail_slug).css('display', 'none')
						$('.post_added-'+ post_detail_slug).html('<button class="btn btn-disabled">Added to favorites</button>')
					}
				})
			})
		})
	</script>
{% endblock %}

mainApp/templates/mainApp/posts.html
{% extends "mainApp/wrapper.html" %}

{% block content %}
	<!--post view
	{% for i in posts%}
		<h3><a href="">{{ i.title }}</a></h3>
		<h6>{{ i.date_published }}</h6>
	{%  endfor %}-->
	{% for i in posts %}
		<div class="span8">
	    	<h1><a href="{% url 'post_detail' i.category.slug i.slug %}">{{ i.title }}</a></h1>
	    		<p>{{ i.text_preview }}</p>
		    <div>
		        <span class="badge badge-success">Posted {{ i.date_published }}</span>
		        <span class="pull-right"><a href="#">{{ i.user }}</a></span>
		    </div> 
		    <hr>
		</div>
	{% endfor %}

	<div class="pagination">
	    <span class="step-links">
	        {% if posts.has_previous %}
	            <a href="?page=1">&laquo; first</a>
	            <a href="?page={{ posts.previous_page_number }}">previous</a>
	        {% endif %}

	        <span class="current">
	            Page {{ posts.number }} of {{ posts.paginator.num_pages }}.
	        </span>

	        {% if posts.has_next %}
	            <a href="?page={{ posts.next_page_number }}">next</a>
	            <a href="?page={{ posts.paginator.num_pages }}">last &raquo;</a>
	        {% endif %}
	    </span>
	</div>
{% endblock %}

mainApp/templates/mainApp/registration.html
{% extends "mainApp/wrapper.html" %}

{%  load crispy_forms_tags %}

{%  block content %}
	<div class="container">
		<h4>Registration</h4>
		<div class="row">
			<div class="col-sm-6 col-sm-offset-2">
				<form action="" method="POST">
					{{  form.error }}
					{% csrf_token %}
					{{  form|crispy }}
					<input type="submit" value="Registrate">
				</form>
			</div>
		</div>
	</div>
{% endblock %}

mainApp/templates/mainApp/user_detail.html
{% extends "mainApp/wrapper.html" %}

{% block content %}
	<div class="container-fluid well span6">
	<div class="row-fluid">
       
        <div class="span8">
            <h3>Username: {{ current_user.nick }}</h3>
            <h3>Email: {{ current_user.email }}</h3>
            <h3>Fullname: {{ current_user.full_name }}</h3>
            <hr>
            <h3>Favorite posts:</h3>
            <ul>
            	{%  for favorite_post in current_user.favorite_posts.all %}
            		<li>
            			<a href="{% url 'post_detail' favorite_post.category.slug favorite_post.slug %}">
                            {{ favorite_post.title }}
                        </a>
            		</li>
            	{% endfor %}
            </ul>
        </div>
        
        
        <!--
        <div class="span2">
            <div class="btn-group">
                <a class="btn dropdown-toggle btn-info" data-toggle="dropdown" href="#">
                    Action 
                    <span class="icon-cog icon-white"></span><span class="caret"></span>
                </a>
                <ul class="dropdown-menu">
                    <li><a href="#"><span class="icon-wrench"></span> Modify</a></li>
                    <li><a href="#"><span class="icon-trash"></span> Delete</a></li>
                </ul>
            </div>
        </div>
    	-->
</div>
</div>
{% endblock %}

mainApp/templates/mainApp/wrapper.html
<!DOCTYPE html>
<html lang="en">

<head>
	<meta charset="utf-8">
	<title>BLogo</title>
	{% load static %}
	<link rel="stylesheet" type="text/css" href="{% static 'css/bootstrap.min.css' %}">
  <link rel="stylesheet" type="text/css" href="{% static 'css/header-navigation.css' %}">
  <link rel="stylesheet" type="text/css" href="{% static '/bootstrap4-glyphicons/maps/glyphicons-fontawesome.min.css' %}">
  <script src="{% static 'js/jquery.min.js' %}"></script>
  <script src="{% static 'js/bootstrap.min.js' %}"></script> <!--smth like that-->
  
</head>

<body>

  <div class="page-header">
          <div class="container">
            <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
              <a href="/" class="navbar-brand">BLogo</a>
              <button class="navbar-toggler" data-target="#navigation" data-control="navigation" data-toggle="collapse">
                <span class="navbar-toggler-icon"></span>
              </button>
              <div class="collapse navbar-collapse" id="navigation">
                <ul class="nav navbar-nav">         
                  <li class="nav-item">
                    <a href="/posts" class="nav-link">Posts</a>
                  </li>
                  
                  <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" data-toggle="dropdown" id="preview" href="#" role="button" aria-haspopup="true" aria-expanded="false">Categories</a>
                    <div class="dropdown-menu" aria-lableledby="preview">
                      {% for cat in categories%}
                        <a class="dropdown-item" href="{% url 'category_detail' cat.slug %}">{{ cat.name }}</a>
                      {% endfor %}
                    </div>
                  </li>
                  
                  <li class="nav-item">
                    <a href="/contacts" class="nav-link">Contact Us</a>
                  </li>

                  {% if not request.user.is_authenticated %}
                    <li class="nav-item">
                      <a href="{% url 'login_page' %}" class="nav-link">Login</a>
                    </li>
                    <li class="nav-item">
                      <a href="{% url 'registration' %}" class="nav-link">Sign in</a>
                    </li>
                  {% else %}
                    <li class="nav-item">
                      <a href="{% url 'logout_action' %}" class="nav-link" >Logout</a>
                    </li>
                    <li>
                      <p class="nav-item" style="color: yellow;">Hello, {{ request.user }}</p>
                    </li>
                    
                  {% endif %}

                  {% if request.user.is_authenticated %}
                    <li class="nav-item  navbar-right">
                      <a href="{% url 'user_detail' request.user %}" class="nav-link">Profile</a>
                    </li>
                  {% endif %}

                </ul>
            </div>
          </nav>
              <div class="row">
                  <div class="col-xl-12 col-lg-12 col-md-12 col-sm-12 col-12">
                      <div class="page-caption">
                          <h1 class="page-title">BLogo</h1>
                          <h1 class="page-title-min">We bring ideas in the real life</h3>
                      </div>
                  </div>
              </div>
          </div>
  </div>

  <div class="card-section">
          <div class="container">
              <div class="card-block bg-white mb30">
                  <div class="row">
                      <div class="col-xl-12 col-lg-12 col-md-12 col-sm-12 col-12">
                          <!-- jinja should be here -->
                          {% block content %}
                            <div class="section-title mb-0" align="center">
                              <h2>Make your dreams come true</h2>
                              <p>
                                Our approach is very simple: we define your problem and give the best solution. 
                              </p>
                            </div>
                          {% endblock %}
                          <!-- jinja should be here -->
                      </div>
                  </div>
              </div>
              <div class="row">
                  <div class="col-xl-12 col-lg-12 col-md-12 col-sm-12 col-12 text-center">
                    <br>
                    Created by @Shrrgn
                  </div>
              </div>
          </div>
  </div>

</body>

</html>